services:
  _instanceof:
    Symfony\Component\EventDispatcher\EventSubscriberInterface:
      tags: ['app.event_subscriber']

  _defaults:
    autowire: true
  App\:
    resource: '../src/*'

  App\Controller\OrderController:
    public: true

  App\Listener\OrderSmsListener:
    tags:
      [
        {
          name: "app.event_listener",
          event: order.afet_insert,
          method: sendSmsToStock,
          priority: 3
        },
        {
          name: "app.event_listener",
          event: order.after_insert,
          method: sendSmsToStock,
          priority: 2
        }
      ]

  Symfony\Component\EventDispatcher\EventDispatcher:
    public: true
    #calls:
    #  - method: "addListener"
    #    arguments:
    #      - order.after_insert
    #      - ['@App\Listener\OrderSmsListener', "sendSmsToStock"]
    #      - 3
    #  - method: "addListener"
    #    arguments:
    #      - order.after_insert
    #      - ['@App\Listener\OrderSmsListener', "sendSmsToCustomer"]
    #      - 2
    #  - method: "addSubscriber"
    #    arguments:
    #      - '@App\Listener\OrderEmailsSubscriber'
