services:
  _defaults:
    autowire: true
  App\:
    resource: '../src/*'

  App\Controller\OrderController:
    public: true

  Symfony\Component\EventDispatcher\EventDispatcher:
    public: true
    calls:
      - method: "addListener"
        arguments:
          - order.after_insert
          - ['@App\Listener\OrderSmsListener', "sendSmsToStock"]
          - 3
      - method: "addListener"
        arguments:
          - order.after_insert
          - ['@App\Listener\OrderSmsListener', "sendSmsToCustomer"]
          - 2
      - method: "addSubscriber"
        arguments:
          - '@App\Listener\OrderEmailsSubscriber'
